<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Pacific Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="" host="LAPTOP-VE86FS4A"><DocLocation><![CDATA[C:\Users\zahid\Desktop\Mokter\UFTAutomationFramework]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[UFTAutomationFramework]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj ><![CDATA[****************************Start Executing Test Name: Test2**************************************]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:12]]></Time>
<TimeTick>1479787572</TimeTick>
<NodeArgs eType="User" icon="4" nRep="7" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[****************************Start Executing Test Name: Test2**************************************]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:13]]></Time>
<TimeTick>1479787573</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:14]]></Time>
<TimeTick>1479787574</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "https://www.facebook.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://www.facebook.com/",1]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:14]]></Time>
<TimeTick>1479787574</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Passed" >
<Disp><![CDATA[Run "https://www.facebook.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mmhusabd@gmail.com"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:17]]></Time>
<TimeTick>1479787577</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[[ email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ pass ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Tarash6780"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:18]]></Time>
<TimeTick>1479787578</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="19" >
<Disp><![CDATA[[ pass ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Log In ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:19]]></Time>
<TimeTick>1479787579</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[[ Log In ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:23]]></Time>
<TimeTick>1479787583</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DrMokter Hossain"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:25]]></Time>
<TimeTick>1479787585</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:28]]></Time>
<TimeTick>1479787588</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:30]]></Time>
<TimeTick>1479787590</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="33" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahima Mokter"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:32]]></Time>
<TimeTick>1479787592</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:34]]></Time>
<TimeTick>1479787594</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:37]]></Time>
<TimeTick>1479787597</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mosaddek Mahdi"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:39]]></Time>
<TimeTick>1479787599</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="44" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:41]]></Time>
<TimeTick>1479787601</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:44]]></Time>
<TimeTick>1479787604</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nolin Ahmed Mamun"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:46]]></Time>
<TimeTick>1479787606</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:48]]></Time>
<TimeTick>1479787608</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ userNavigationLabel ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:50]]></Time>
<TimeTick>1479787610</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" >
<Disp><![CDATA[[ userNavigationLabel ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Log Out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:53]]></Time>
<TimeTick>1479787613</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="60" >
<Disp><![CDATA[[ Log Out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Facebook - Log In or Sign Up ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:55]]></Time>
<TimeTick>1479787615</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="62" >
<Disp><![CDATA[[ Facebook - Log In or Sign Up ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[----------------------------End  Executing Test Name: Test2----------------------------------------]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:55]]></Time>
<TimeTick>1479787615</TimeTick>
<NodeArgs eType="User" icon="4" nRep="63" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[----------------------------End  Executing Test Name: Test2----------------------------------------]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[****************************Start Executing Test Name: Test2**************************************]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:55]]></Time>
<TimeTick>1479787615</TimeTick>
<NodeArgs eType="User" icon="4" nRep="64" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[****************************Start Executing Test Name: Test2**************************************]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:56]]></Time>
<TimeTick>1479787616</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="66" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:56]]></Time>
<TimeTick>1479787616</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Run "https://www.facebook.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://www.facebook.com/",1]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:56]]></Time>
<TimeTick>1479787616</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="70" status="Passed" >
<Disp><![CDATA[Run "https://www.facebook.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="69" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mmhusabd@gmail.com"]]></Details>
<Time><![CDATA[11/21/2016 - 20:06:59]]></Time>
<TimeTick>1479787619</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="73" >
<Disp><![CDATA[[ email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ pass ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Tarash6780"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:00]]></Time>
<TimeTick>1479787620</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="76" >
<Disp><![CDATA[[ pass ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ Log In ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:01]]></Time>
<TimeTick>1479787621</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" >
<Disp><![CDATA[[ Log In ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:04]]></Time>
<TimeTick>1479787624</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DrMokter Hossain"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:06]]></Time>
<TimeTick>1479787626</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:09]]></Time>
<TimeTick>1479787629</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="87" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:11]]></Time>
<TimeTick>1479787631</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="90" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahima Mokter"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:13]]></Time>
<TimeTick>1479787633</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="93" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:15]]></Time>
<TimeTick>1479787635</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="95" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:18]]></Time>
<TimeTick>1479787638</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="98" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mosaddek Mahdi"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:20]]></Time>
<TimeTick>1479787640</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="101" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:22]]></Time>
<TimeTick>1479787642</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="103" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:24]]></Time>
<TimeTick>1479787644</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nolin Ahmed Mamun"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:27]]></Time>
<TimeTick>1479787647</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="109" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:29]]></Time>
<TimeTick>1479787649</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="111" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ userNavigationLabel ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:31]]></Time>
<TimeTick>1479787651</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="114" >
<Disp><![CDATA[[ userNavigationLabel ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Log Out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:33]]></Time>
<TimeTick>1479787653</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="117" >
<Disp><![CDATA[[ Log Out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Facebook - Log In or Sign Up ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:35]]></Time>
<TimeTick>1479787655</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="119" >
<Disp><![CDATA[[ Facebook - Log In or Sign Up ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[----------------------------End  Executing Test Name: Test2----------------------------------------]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:36]]></Time>
<TimeTick>1479787656</TimeTick>
<NodeArgs eType="User" icon="4" nRep="120" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[----------------------------End  Executing Test Name: Test2----------------------------------------]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[****************************Start Executing Test Name: Test2**************************************]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:36]]></Time>
<TimeTick>1479787656</TimeTick>
<NodeArgs eType="User" icon="4" nRep="121" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[****************************Start Executing Test Name: Test2**************************************]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:37]]></Time>
<TimeTick>1479787657</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="123" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:37]]></Time>
<TimeTick>1479787657</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Run "https://www.facebook.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://www.facebook.com/",1]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:37]]></Time>
<TimeTick>1479787657</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="127" status="Passed" >
<Disp><![CDATA[Run "https://www.facebook.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="126" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mmhusabd@gmail.com"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:41]]></Time>
<TimeTick>1479787661</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="130" >
<Disp><![CDATA[[ email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ pass ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Tarash6780"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:42]]></Time>
<TimeTick>1479787662</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="133" >
<Disp><![CDATA[[ pass ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Log In ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:43]]></Time>
<TimeTick>1479787663</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="136" >
<Disp><![CDATA[[ Log In ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:46]]></Time>
<TimeTick>1479787666</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="139" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DrMokter Hossain"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:49]]></Time>
<TimeTick>1479787669</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="142" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:51]]></Time>
<TimeTick>1479787671</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="144" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:53]]></Time>
<TimeTick>1479787673</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="147" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahima Mokter"]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:55]]></Time>
<TimeTick>1479787675</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="150" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:07:58]]></Time>
<TimeTick>1479787678</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="152" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:00]]></Time>
<TimeTick>1479787680</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="155" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mosaddek Mahdi"]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:02]]></Time>
<TimeTick>1479787682</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="158" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:05]]></Time>
<TimeTick>1479787685</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="160" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ Find Friends ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:07]]></Time>
<TimeTick>1479787687</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="163" >
<Disp><![CDATA[[ Find Friends ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Search ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nolin Ahmed Mamun"]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:09]]></Time>
<TimeTick>1479787689</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="166" >
<Disp><![CDATA[[ Search ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ Search ].DoubleClick]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:11]]></Time>
<TimeTick>1479787691</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="168" >
<Disp><![CDATA[[ Search ].DoubleClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ userNavigationLabel ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:13]]></Time>
<TimeTick>1479787693</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="171" >
<Disp><![CDATA[[ userNavigationLabel ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Log Out ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:16]]></Time>
<TimeTick>1479787696</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="174" >
<Disp><![CDATA[[ Log Out ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Facebook - Log In or Sign Up ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:18]]></Time>
<TimeTick>1479787698</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="176" >
<Disp><![CDATA[[ Facebook - Log In or Sign Up ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj ><![CDATA[----------------------------End  Executing Test Name: Test2----------------------------------------]]></Obj>
<Details ><![CDATA[]]></Details>
<Time><![CDATA[11/21/2016 - 20:08:18]]></Time>
<TimeTick>1479787698</TimeTick>
<NodeArgs eType="User" icon="4" nRep="177" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[----------------------------End  Executing Test Name: Test2----------------------------------------]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/21/2016 - 20:06:12" eTime="11/21/2016 - 20:08:18" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="11/21/2016 - 20:06:12" eTime="11/21/2016 - 20:08:18" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test UFTAutomationFramework Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>